### ISSUE TITLE
modbus module  Log I/O enabled,when Files to keep  change from big number to small,will error

### ISSUE THREAD

**Issue by minghu** [infiniteautomation/ma-modules-public#11]
modbus module  Log I/O enabled,when Files to keep  change from big number to small,for example ,Files to keep  change from 5 to 3,will cause   ERROR 2015-07-14 11:47:15,399 (com.serotonin.log.RollingIOLog.sizeCheck:85) - java.nio.file.NoSuchFileException: D:\mango2\mango_automation_2.5.2_enterprise_demo\logs\modbusIO-3.log.3,

suggest,when datasource initializing,if the exist iolog count is more then configuration,delete the more.

 another bug,the iolog file is not thorough closed when datasource stoped, you can enabled/disabled many times,then when the iofiles's sizes  reached (File Size (in MB)),will cause iofiles being used error,can't  rename it.

**Comment by Puckfist** [comment]
The logging system was recently updated.

I have tested this on a Modbus IP log in Mango 2.8, it was on log number 24 and I lowered it to a limit of 2 and multiple enable / disables, and no errors evince themselves.

Thanks for bringing this to our attention!
