### ISSUE TITLE
meta datasource initializing when occer an Exception, the meta datasource status is wrong

### ISSUE THREAD

**Issue by minghu** [infiniteautomation/ma-modules-public#12]
when a  meta datasource initializing,if occer   Point disabled or does not exist 
com.serotonin.m2m2.rt.script.DataPointStateException
	at com.serotonin.m2m2.rt.script.ScriptExecutor.convertScriptContext(ScriptExecutor.java:64)

then,the datasource status actually is not initializing sucess,it need back to stoped status,but it's status is running.

**Comment by terrypacker** [comment]
The Meta Data source will try to initialize the data point on every poll, so if it fails at startup it can still begin operating when all it's context point are available.  An event is raised if a point fails due to context problems.
