### ISSUE TITLE
Internal Data Points need default rollups.  

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-modules-public#122]
The Admin Home page shows error trying to display more than 5000 points on the chart. An average rollup should be fine for the server metrics for memory and CPU.

**Comment by jazdw** [comment]
Fixed this already yesterday - 706a77d951f103f5753c56da70dc67b825a174d2
Wont change points which already exist, so I'll leave this open if you want to fix that.

**Comment by terrypacker** [comment]
Closing as acceptable
