### ISSUE TITLE
Error when deleting a watchlist

### ISSUE THREAD

**Issue by stevededrick** [infiniteautomation/ma-modules-public#13]
PreparedStatementCallback; SQL [INSERT INTO selectedWatchList (userId, watchListId) VALUES (?,?)]; Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.SELECTEDWATCHLIST(USERID)"; SQL statement:
INSERT INTO selectedWatchList (userId, watchListId) VALUES (?,?) [23505-181]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.SELECTEDWATCHLIST(USERID)"; SQL statement:
INSERT INTO selectedWatchList (userId, watchListId) VALUES (?,?) [23505-181]

I was cleaning up some watchlist's that had no points in them any longer and got this error.

**Comment by Puckfist** [comment]
Confirmed. We are handling all issues in the main repo at the moment, so I'm going to start a new issue there and include a link and replication instructions.
