### ISSUE TITLE
Confused about user "Send alarm emails" option

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-modules-public#21]
In the new UI for the help it says:

Selecting a Send alarm emails alarm level above Ignore will cause these notifications to be sent when the event's alarm level is greater than or equal to the user's minimum alarm level,

I think we should add something like: "Set to 'Ignore' for no emails to be sent"

**Comment by Puckfist** [comment]
This was in the ma-dashboards repo but I have made this change in the linked commit
