### ISSUE TITLE
Point Values v2 REST API Performance Improvements

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-modules-public#52]
It has been seen that making a very large Point Value Rollup request via the API can cause Mango to crash, I investigated to see if there is a memory leak but this does not appear to be the case.  It seems that a large amount of garbage is generated during these calls and is likely the culprit.

One suggestion was to create a system setting or use the existing UI setting (stored in the json data store) to do a quick calculation that would prevent returning too many values.  However we need to consider that non web UI requests will be made to this endpoint so a limit for what the browser can handle will not be the same as what the limit for the max of the Mango server will be.

```
{
  "xid" : "mangoUI-settings",
  "name" : "UI Settings",
  "modelType" : "JSON_DATA",
  "validationMessages" : [ ],
  "readPermission" : "",
  "editPermission" : "edit-ui-settings",
  "publicData" : true,
  "jsonData" : {
    "pointValuesLimit" : 10000
  },
  "id" : 3
}
```

**Comment by terrypacker** [comment]
This mainly has to do with the eTag filter in the Core but also I have made improvements to the garbage generation in the above commit.  The node tests do cover the code that is changed for this so we can be reasonably confident no bugs have been introduced in the accuracy of a single point rollup results.

To test the memory consumption use the MangoApi/api-test/pointValueStream.spec.js test and modify the file size to suit.

**Comment by jazdw** [comment]
> The node tests do cover the code that is changed for this so we can be reasonably confident no bugs have been introduced in the accuracy of a single point rollup results.

I would be very surprised if we have tests that check the accuracy of the values when using rollups.

**Comment by terrypacker** [comment]
I believe you wrote this test, pretty smart idea actually!
```
    it('Returns the same point values using a FIRST rollup with same time period as poll period', function() {
        return client.pointValues.forTimePeriod({
            xid: testPointXid1,
            from: startTime,
            to: endTime,
            rollup: 'FIRST',
            timePeriod: {
                periods: 1,
                type: 'SECONDS'
            }
        }).then(result => {
            assert.isArray(result);
            assert.strictEqual(result.length, pointValues1.length);

            result.forEach((pv, i) => {
                assert.strictEqual(pv.value, pointValues1[i].value);
                assert.strictEqual(pv.timestamp, pointValues1[i].timestamp);
            });
        });
    });
```
