### ISSUE TITLE
Point links that don't "Write annotation" produce NPE in PointValueTimeModel

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#57]
This is because the point link returns an AnnotatedPointValueTime with a sourceMessage that is null. Probably the solution is to not return such a thing, but perhaps also AnnotatedPointValueTime should do a null check in getAnnotation() ?

**Comment by Puckfist** [comment]
The NPE prevents the values from being published in websockets

**Comment by terrypacker** [comment]
Fixed via AnnotatedPointValueTime using null check
