### ISSUE TITLE
Watch list set point dialogue doesn't close upon set

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#63]
Upon setting a value to my virtual point, the set point window stayed open, and as I mashed enter I set that point more and more times. I think it should close with each set, but could be interested in arguments on other use cases.

**Comment by terrypacker** [comment]
@pierpuccini first test this to make sure it is still staying open, if so discuss with @jazdw to decide if we want to change it or close this issue.

**Comment by pierpuccini** [comment]
Issue appears to be occurring in ma-dashboards repo. I have a potential fix that needs revision from @jazdw

**Comment by jazdw** [comment]
@Joelhaggar please confirm that you want the set point value dialog to close after setting it once.
