### ISSUE TITLE
Virtual data point sinusoidal numeric phase shift not getting saved in new UI

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#64]
If I set a value to the phase shift field in the new UI for a Numeric data point with a sinusoidal change type on a virtual data source, I see that save as 0 in the code and then upon reopening the page nothing is displayed in the phase shift field.

**Comment by guetteluis** [comment]
@Puckfist @jazdw the problem is that the phase shift is not available in the model:
<img width="647" alt="Screen Shot 2019-08-16 at 11 38 01 AM" src="https://user-images.githubusercontent.com/35845741/63181283-a1a46180-c01d-11e9-98e7-7f2edb504c02.png">

**Comment by Puckfist** [comment]
It's got an @JsonIgnore in the model, huh
