### ISSUE TITLE
Virtual data source multistate no change type doesn't display states list or start value when existing point is edited

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#66]
Create multistate point with no change change type, define states and a start value and save it. Edit it again and no states appear in the state list!

I was only able to observe this with the no change change type.

**Comment by guetteluis** [comment]
@Puckfist @jazdw I see that when the datapoint is saved, the states are sent in the `values` variables:
<img width="647" alt="Screen Shot 2019-08-16 at 12 33 41 PM" src="https://user-images.githubusercontent.com/35845741/63183160-53de2800-c022-11e9-9388-d33d426f504d.png">

Then, in the response I get:
<img width="647" alt="Screen Shot 2019-08-16 at 12 33 55 PM" src="https://user-images.githubusercontent.com/35845741/63183194-6bb5ac00-c022-11e9-8602-a6f6bb3029d2.png">

**Comment by terrypacker** [comment]
@guetteluis @Puckfist if you look at the legacy UI this will make more sense.  A multistate no change type point doesn't have any states.  It only has a start value.  So sending states via the REST api has no effect.

**Comment by terrypacker** [comment]
@guetteluis just remove the states input from the UI for this type of point.

**Comment by jazdw** [comment]
Agreed with @terrypacker values are not used for "no change" point locators. You can still supply a list of values and their rendered text on the text renderer.
