### ISSUE TITLE
Watchlist builder for static watchlists could use new data point selector

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#67]
The new data point selector is snazzy in providing tag access and many columns to sort / filter by, as well as make multiple selections at once. This could enable people to efficiently create the static watch list they are seeking in the watch list builder.

**Comment by jazdw** [comment]
Fixed in infiniteautomation/ma-dashboards@52a039ed5623d4dc4dd5363f9d87b89f366ae626
