### ISSUE TITLE
datatype is ALPHANUMERIC, Data length can not exceed 65536

### ISSUE THREAD

**Issue by 190948804** [infiniteautomation/ma-modules-public#69]
when we write pointValueTime to one point, the value is a long string, the datatype is ALPHANUMERIC, not written successfully. but we reduce the length of the input value, the written is successful。when we set  a long string value on the page to the point, the error log is "com.infiniteautomation.tsdb.IasTsdbRecordSizeException: Data length can not exceed 65536".

Are these two situations related? And whether the maximum data length is limited

**Comment by terrypacker** [comment]
Yes they are related and yes the max bytes storable in a single Mango NoSQL entry is 65536.  If necessary you could get around this by using H2 or MySQL instead of the Mango NoSQL module.
