### ISSUE TITLE
Point values endpoints don't expose FireEvents setting

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-modules-public#76]
the DataPointRT savePointValueDirectToCache method was modified to enable creating event tasks for values in certain situations, but the old helper method defaults to never. This is not exposed on something like the /rest/v2/point-values endpoints, so the POST endpoint for instance never fires event notify items.

This is a related issue in the core: https://github.com/infiniteautomation/ma-core-public/issues/1322.

**Comment by terrypacker** [comment]
So just to confirm you would want to expose this setting on the endpoint(s) perhaps on a per-point basis?
```
{ fireEvents: [ALWAYS, NEVER, ON_CURRENT_VALUE_UPDATE] ...
}
```

**Comment by terrypacker** [comment]
Also it should be noted that there is a new endpoint for 3.7.0 that should be modified:
`/v2/point-value-modification/import`

**Comment by terrypacker** [comment]
I've removed the method that doesn't accept a FireEvent parameter and fixed all the places that used the old one.  I'm going to close this issue and open a new one for the option to expose these settings in the various other places that it might be useful.  The commits for those changes will be on that issue.
