### ISSUE TITLE
SST Graphics - Graphics added to overrides path do not show up in Graphic view

### ISSUE THREAD

**Issue by stevededrick** [infiniteautomation/ma-modules-public#9]
I added a custom image pack to: Mango ▸ overrides ▸ web ▸ modules ▸ sstGraphics ▸ web ▸ graphics ▸ custom ▸ LEDsmall.  It was only accessible to Graphic Views when I place the files directly under the module.

**Comment by Puckfist** [comment]
SST Graphics now has a persisting folder in the module's web/ directory that one can place their graphics in, that do show up. So this is closed.
